# Monitoring Integration for Chaos Engineering in JadeVectorDB
# This configuration integrates chaos experiments with existing monitoring systems

---
# Prometheus rules to detect issues during chaos experiments
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: chaos-engineering-rules
  namespace: jadevectordb-system
spec:
  groups:
  - name: chaos-engineering.rules
    rules:
    - alert: ChaosExperimentStarted
      expr: max_over_time(chaos_experiment_active[5m]) == 1
      for: 0m
      labels:
        severity: info
      annotations:
        summary: "Chaos experiment is active"
        description: "A chaos engineering experiment is currently active in the system"
        
    - alert: HighErrorRateDuringChaos
      expr: 100 * (rate(jadevectordb_requests_total{status=~"5.."}[5m]) or vector(0)) / rate(jadevectordb_requests_total[5m]) > 10
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "High error rate during chaos experiment"
        description: "More than 10% of requests are resulting in 5xx errors during chaos experiment"
        
    - alert: HighLatencyDuringChaos
      expr: histogram_quantile(0.95, rate(jadevectordb_request_duration_seconds_bucket[5m])) > 5
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "High latency during chaos experiment"
        description: "95th percentile of request duration is higher than 5 seconds during chaos experiment"
        
    - alert: PodCrashDuringChaos
      expr: changes(kube_pod_status_phase{phase="Failed", pod=~"jadevectordb-.*"}[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "Pod crashed during chaos experiment"
        description: "A JadeVectorDB pod crashed during the chaos experiment"
        
    - alert: NodeDownDuringChaos
      expr: up{job=~"jadevectordb-.*"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Node down during chaos experiment"
        description: "A JadeVectorDB node is down during the chaos experiment"
        
    - alert: MemoryPressureDuringChaos
      expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High memory pressure during chaos experiment"
        description: "Available memory is less than 10% of total during chaos experiment"
        
    - alert: CPUHighUsageDuringChaos
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage during chaos experiment"
        description: "CPU usage is higher than 90% during chaos experiment"

---
# ServiceMonitor to collect chaos metrics from the chaos tools
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chaos-engineering-monitor
  namespace: jadevectordb-system
spec:
  selector:
    matchLabels:
      app: chaos-engineering
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics