# Default values for jadevectordb Helm chart

# Global Docker image parameters
image:
  repository: jadevectordb/jadevectordb
  tag: latest
  pullPolicy: IfNotPresent

# JadeVectorDB service configuration
jadevectordb:
  # Number of replicas for standalone deployment
  replicaCount: 1
  
  # JadeVectorDB configuration
  config:
    logLevel: INFO
    port: 8080
    rpcPort: 8081
    
  # Resource limits and requests
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
      
  # Service configuration
  service:
    type: ClusterIP
    port: 8080
    rpcPort: 8081
    
  # Persistence configuration
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    
  # Environment variables
  env: {}

# Cluster mode configuration
cluster:
  enabled: false
  size: 3
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  persistence:
    size: 50Gi
    storageClass: ""

# Monitoring configuration
monitoring:
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Node selectors and tolerations
nodeSelector: {}

tolerations: []

affinity: {}